version: "3.7"
services:
 db:
   image: postgres:13.7
   restart: always
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     PGDATA: /var/lib/postgresql/data
   volumes:
    - db-data:/var/lib/postgresql/data
   ports:
    - "15432:5432"
 
 pgadmin:
   image: dpage/pgadmin4:latest
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
    - "8080:80"
   volumes:
    - pgadmin-data:/var/lib/pgadmin
   links:
    - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data: